In [1]:
l1 = [ 5,2, 10 ]
l1*2 #곱하기 결과가 아님.
l1[ 1 ] #indexing
l1[ 1:3 ] #slicing  시작위치:끝나는위치
l2 = ["abc", True, l1]
l2.append( 1000000 ) #원소 추가
l2.extend( l1 ) #리스트 연결
l3 = []
l3.append(1)

In [2]:
d1 = { 0:l1, 1:l2, "sam":1   }  #dictionary
d1["sam"]

1

In [3]:
if 50 > 40 :
    print("탕수육")
elif 2<1:
    print("aaa")
else :
    print("김치")
l1 = [ 5,2, 10 ]
l3 = []
for i in l1:
  if i >= 5:
    l3.append(i*2)  
[     i*2    for i in l1   if i >=5            ]

탕수육

[10, 20]

In [4]:
!pip install numpy pandas -q 
#패키지 설치

In [5]:
import numpy as np 
ar1 = np.array( l1   ) *2  #array, vector
ar1[2] #indexing, slicing 가능

np.int64(20)

In [6]:
l6 = [ [ 1,2], [3,4]  ] #nested 
ar2 = np.array( l6 )
ar1.shape, ar2.shape
ar2[ 0:2,0 ] #ar2[ 행 , 열 ]  # indexing, slicing.
ar2.reshape(4).reshape( 2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
import pandas as pd
l6 = [ [ 1,2,3], [4,5,6],[7,8,9]  ] #nested 
ar2 = np.array( l6 )
df1 = pd.DataFrame( ar2, index=["r1","r2","r3"], 
                   columns=["c1","c2", "c3"] )   
#1~9까지 값을 갖는 3행3열 데이터프레임, r1,r2,r3, c1,c2,c3
df1["c1"]
df1.c1
df1.iloc[ 0:2, 1:3]  #array 인덱싱,슬라이싱, , :는 전체 슬라이싱
df1[["c1", "c2"]] #df1.info() 
df1.describe()
df1.to_csv("df1.csv" )
pd.read_csv( "df1.csv")
#creditset2.csv 를 읽어서 df2라는 데이터프레임 만들어보세요

In [ ]:
df2 = pd.read_csv("creditset2.csv", )
      # header=None,index_col=1,skiprows=2,parse_dates=
#df2.columns, df2.index, df2.values
df2.default10yr.value_counts()/2000
df2["age2"] = df2.age > 50 
df2["income2"] = df2.income > df2.income.mean()
df2.income2.value_counts()

In [41]:
# binary.csv, df3, info, admit 비율, rank 비율, 
# gre 평균보다 큰지를 gre2 컬럼으로 생성
# csv 저장해보세요.  to_csv(  )
df3 = pd.read_csv("binary.csv")
#df3.info()
df3["rank"].value_counts()
df3["gre2"] = df3["gre"]> df3["gre"].mean()
df3.to_csv("binary2.csv")

In [ ]:
import os
os.getcwd()   
files = os.listdir()
files2 = [ i for i in files if i.endswith(".csv")]

#files2의 파일들 각각 데이터프레임으로 읽으셔서, flist라는 비어있는 리스트에 하나씩 추가해주세요.
flist = []

for i in files2:
    flist.append( pd.read_csv(i)       )

len(flist)
flist[0]

In [ ]:
# 1. query
df3 = pd.read_csv("binary.csv")
df3.query("admit==1 & rank==4")     

#합격자 중에서 1등급과 4등급의 gre, gpa 점수차이 비교해보세요. #sqldf
df3.query("admit==1 & rank==4")[["gre", "gpa"]].mean()
df3.query("admit==1 & rank==1")[["gre", "gpa"]].mean()

df3["admit"] = df3.admit.astype("str")
df3.query("(admit=='1' | rank==1)") #or

In [ ]:
# 2. groupby  #pivot, pivot_table
df3 = pd.read_csv("binary.csv")
df3.groupby(["admit", "rank"]).mean()[["gre","gpa"]]

In [ ]:
# creditset2.csv -> df9 -> default10yr가 1인 레코드만 query
# 나이가 30세 이상, 미만, income, loan의 평균 비교 groupby
df9 = pd.read_csv("creditset2.csv")
df9 = df9.query("default10yr==1")
df9["age30"] = df9.age>=30
df9.groupby("age30")[["income","loan"]].mean()

In [ ]:
# 3 sample sort_values
df9.sample(5).sort_values("income", ascending=False)

In [ ]:
# 4. 치환, replace, cp949
df10 = pd.read_csv("train_df.csv", encoding="cp949")
df10.발화자.replace( { "c":"Customer", "s":"Support"})#c->Customer, s->Support  
df10.인텐트.str.replace( {"교환|반품|환불_":""})  #부분적 치환 가능
df10.발화문.str.replace( "[^가-힣]", " ", regex=True) #한글만 남기기
#패턴 예: [a-f],  [가-힣], [가-잏], [0-3], [0-3]*

In [ ]:
# 5 함수 정의 apply
#np.where (엑셀의 if)
np.where( df9.income > 40000, "large", "small")

def func1(x):    
  if x.endswith("요청"):
    return 1
  elif x.endswith("확인"):
    return 2
  else:
    return 3
df10 = pd.read_csv("train_df.csv", encoding="cp949")
df10.인텐트.apply(func1)  #Split Apply Combine, df9.apply(func1)

#df10의 인텐트에 대해서, 각 값이 '요청'으로 끝나는 경우에는 1을 반환, 확인->2, 그 외 3을 반환

In [ ]:
#6 merge, concat
#df11_1은 3행 2열, r1, r2, r3,    c1, c2
#df11_2는 3행 2열, r2, r3, r4,    c2, c3
arr = np.array([  [1,2],   [3,4],    [5,6]   ])
df11_1 = pd.DataFrame( arr, index=["r1","r2","r3"], columns=["c1","c2"])
df11_2 = pd.DataFrame( arr, index=["r2","r3","r4"], columns=["c2","c3"])
df11_1+df11_2 #NaN: 결측 코드, np.nan
df11_3 = pd.merge( df11_1, df11_2, left_index=True, right_index=True)  
pd.concat([df11_1, df11_2, df11_1], axis=1 )
#df0.csv, df1.csv를 각각 df12_1, df12_2로 읽으세요.
df12_1 = pd.read_csv("df0.csv", parse_dates=[0])#, index_col=0)
df12_2 = pd.read_csv("df1.csv", parse_dates=[0])#, index_col=0)
pd.merge( df12_1, df12_2, on="date")

In [ ]:
# 7 결측치 체크, 채우기, imputing : NaN (not a number), np.nan
# missing value: NA
# creditApprovalUCI.csv를 읽어서 df13을 만드세요
df13 = pd.read_csv("creditApprovalUCI.csv")
df13.isnull().mean().sort_values(ascending=False)
df13.dropna() #inplace=True 원본에 반영시킬때, #결측이 하나라도 있는 행은 삭제
#수치형, 수치 아닌형으로 컬럼을 분리
df13.select_dtypes(include="number").fillna(0)
df13.select_dtypes(exclude="number").fillna("unk")

In [ ]:
#!pip install scikit-learn -q
from sklearn.impute import SimpleImputer
df13_num = df13.select_dtypes(include="number")
df13_cat = df13.select_dtypes(exclude="number")

imputer = SimpleImputer() #수치mean, median, 수치아닌것 strategy="most_frequent"
imputed = imputer.fit_transform(df13_num) #imputer.fit(데이터프레임) #imputer.transform(데이터프레임)
df13_num_imp = pd.DataFrame(imputed, columns=df13_num.columns)

#범주형(수치아닌형) 변수들에 대한 imputing하셔서 결과를 데이터프레임으로 만들어보세요.
imputer2 = SimpleImputer( strategy="most_frequent" )
imputed2 = imputer2.fit_transform(df13_cat)
df13_cat_imp = pd.DataFrame(imputed2, columns=df13_cat.columns)

#수치형 결과, 범주형결과를 하나의 데이터프레임으로 합쳐보세요.  
pd.concat([df13_num_imp, df13_cat_imp] , axis=1)

In [ ]:
# 8 scaling
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = StandardScaler()
scaled = scaler.fit_transform( df13_num_imp )  
pd.DataFrame( scaled, columns = df13_num_imp.columns  )

#creditset2.csv -> age, loan, income 선택하셔서 MinMaxScaling해보세요.
df14 = pd.read_csv("creditset2.csv")
df14 = df14[["age", "loan", "income"]]
scaler = MinMaxScaler()
scaled = scaler.fit_transform(df14)
pd.DataFrame( scaled, columns=df14.columns)

           age      loan    income
0     1.364333  1.202819  1.453934
1     0.542268  0.696427 -0.762176
2     1.672877  1.174711  0.836821
3     0.363887  0.544980 -0.183070
4    -1.685088  1.420765  1.509563
...        ...       ...       ...
1995  0.572514 -0.826907  0.969747
1996 -1.339834 -0.309130  1.688540
1997 -0.973667  0.354201 -0.071226
1998  1.738021 -0.926756 -0.110003
1999  1.148301  0.963810  1.682986

[2000 rows x 3 columns]

In [ ]:
# mortDefault.csv를 df20으로 읽으시고, info로 확인해 보세요.
# year를 제외한 변수로 사용하세요. 
# replace로 이상한 값(qqq, @@@)을 np.nan으로 치환하세요
# 적절하게 type을 변환하세요
# default에 따른 다른 변수의 평균을 groupby로 비교하세요
# 결측치를 체크한 후, imputing을 해보세요
# scaling을 해보세요.

In [180]:
df20 = pd.read_csv("mortDefault.csv") 
df20.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   creditScore  1000000 non-null  object
 1   houseAge     999999 non-null   float64
 2   yearsEmploy  999999 non-null   float64
 3   ccDebt       1000000 non-null  int64
 4   year         1000000 non-null  int64
 5   default      1000000 non-null  int64
dtypes: float64(2), int64(3), object(1)
memory usage: 45.8+ MB

C:\Users\user\AppData\Local\Temp\ipykernel_11372\217427084.py:1: DtypeWarning: Columns (0: creditScore) have mixed types. Specify dtype option on import or set low_memory=False.
  df20 = pd.read_csv("mortDefault.csv")

In [181]:
df20 = df20[['creditScore', 'houseAge', 'yearsEmploy', 'ccDebt', 'default']]
#df20.drop(columns="year", inplace=True)

In [ ]:
df20.replace({"@@@":np.nan, "qqq":np.nan}, inplace=True)

In [183]:
df20["creditScore"] = df20.creditScore.astype("float")

In [184]:
df20.groupby("default").mean()

         creditScore   houseAge  yearsEmploy       ccDebt
default
0         700.238330  19.968896     5.020985  4912.577865
1         689.140011  21.250596     4.277758  8620.196880

In [186]:
df20.isnull().mean().sort_values(ascending=False)

creditScore    0.000003
houseAge       0.000001
yearsEmploy    0.000001
ccDebt         0.000000
default        0.000000
dtype: float64

In [ ]:
df20_1 = df20.iloc[:, 0:4]
imputer=SimpleImputer()
imputed = imputer.fit_transform(df20_1)

In [189]:
scaler = MinMaxScaler()
scaled = scaler.fit_transform(imputed)
pd.DataFrame(scaled, columns = df20_1.columns)

        creditScore  houseAge  yearsEmploy    ccDebt
0          0.357873     0.500     0.533333  0.301848
1          0.370143     0.275     0.466667  0.383915
2          0.646217     0.425     0.266667  0.496235
3          0.501022     0.550     0.333333  0.257426
4          0.451943     0.375     0.400000  0.461739
...             ...       ...          ...       ...
999995     0.312883     0.725     0.266667  0.231554
999996     0.374233     0.425     0.333333  0.478303
999997     0.400818     0.250     0.600000  0.452019
999998     0.770961     0.325     0.200000  0.111088
999999     0.447853     0.600     0.266667  0.359206

[1000000 rows x 4 columns]

In [ ]:
#df20를 sample(1000) 을 10회 반복하세요
#각 샘플링된 결과를 sample_반복횟수.csv로 저장하세요.
#os.listdir 이용하셔서 하나의 데이터프레임으로 읽으세요.
#문자열+문자열+문자열
#정수 str(정수) ->문자열
#concat, pd.DataFrame(), 여기에 계속 concat으로 데이터프레임 추가해보세요.
for i in [0,1,2,3,4,5,6,7,8,9]: #range(10)
    tmp = "sample_"+str(i)+".csv"
    df20.sample(1000).to_csv(tmp)

In [194]:
files= os.listdir() 
files2= [ i for i in files if i.startswith("sample_")]
result = pd.DataFrame()
for i in files2:
    tmp_df = pd.read_csv(i)
    result = pd.concat([result, tmp_df])
result.shape

(10000, 6)