In [ ]:
print("hellow world")

hellow world

In [ ]:
!pip install pandas

In [ ]:
#리스트
a1 = [  3,10, 21   ]
a1[ 1 ]  #indexing
a1[ 0:2  ] #slicing
a2 = [ 1, "abc", a1]
[a1,a1] #nested list
a1 * 2
#딕셔너리
a3 = { 'a':1,    'b': 2 }  #key:value
a3['a']

In [ ]:
if 3>1:
    print("ok")
elif 3<1:
    print("111")
else:
    print("not ok")
a4 = []  
for i in a1:
  if i >10:
    a4.append( i*2  ) 
[  i*2      for i in a1     if i >9             ]

In [ ]:
#!pip install numpy
import numpy as np
a5 = [[3,4],[7,9]]
a6 = np.array( a5 )    #2D array  
a6.shape
a6[: , 1]  #[행, 열]

In [ ]:
import pandas as pd
a7 = pd.DataFrame( a6, index=["r1", "r2"], columns=["c1","c2"]  )
a7.iloc[0:2,0]  #array의 인덱싱, 슬라이싱, 
a7["c1"] #컬럼명 인덱싱***
a7.c1
a7.iloc[0:2,0:2]  #array의 인덱싱, 슬라이싱, 
a7[["c1", "c2"]]  #a7.values, a7.columns, a7.index
#binary.csv를 다운로드 ->working directory에 넣어주세요
a8 = pd.read_csv("binary.csv")
#a8의 행, 열, 값을 출력, a8.columns
#a8의 열 이름 확인, gre, gpa라는 컬럼만 선택
a8[    ["gre", "gpa"]   ]
#a8의 2-3열, 10~20행 출력해보세요.
a8.iloc[9:20   , 1:3   ]  
#a8.info() , a8.describe()

            admit         gre         gpa       rank
count  400.000000  400.000000  400.000000  400.00000
mean     0.317500  587.700000    3.389900    2.48500
std      0.466087  115.516536    0.380567    0.94446
min      0.000000  220.000000    2.260000    1.00000
25%      0.000000  520.000000    3.130000    2.00000
50%      0.000000  580.000000    3.395000    2.00000
75%      1.000000  660.000000    3.670000    3.00000
max      1.000000  800.000000    4.000000    4.00000

In [ ]:
#train_df.csv를 다운로드->df1로 읽어보세요. read_csv에 encoding="cp949" 지정
df1 = pd.read_csv("train_df.csv", encoding="cp949")
#1
df1.query("발화자=='c' & 상담내순번==1")  #문자열로 조건   "", ''    
#2
df1.drop( columns=["발화문", "상담번호"], inplace=True)  
df1["v1"] = True
#3
df1["인텐트"].value_counts()  #nunique, unique
#4
df1.sort_values("IDX", ascending=False)
#5
pd.read_csv("train_df.csv", encoding="cp949", index_col=0)
#6
df1.dtypes
df1.select_dtypes(exclude="number")  #int, float, number   
#creditset2.csv -> df2에서 default10yr의 0,1의 빈도, default10yr가 1인 행만 선택->df3
df2 = pd.read_csv("creditset2.csv")
df2.default10yr.value_counts()
df3 = df2.query("default10yr==1")
#7
df3.to_csv("test.csv", index=False)
df3.sample(1).to_dict(orient="records")
df3.sample(1).to_json("test.json", orient="records")
#8
df3_1 = df3[["income","age"]]
df3_2 = df3[["loan", "default10yr"]]
#concat
pd.concat([df3, df3, df3 ], axis=1)
#merge: join,,
pd.merge( df3_1, df3_2, left_index=True, right_index=True)
#9: replace
df2["v2"]= df2.default10yr.replace( {1:"default", 0:"normal"}    )   
df2.v2.replace( "[d-e]", "@", regex=True )  
df4 = pd.read_csv("train_df.csv", encoding="cp949")
df4.발화문.replace("[^가-힣]", " ",regex=True) 
#10 type변환
df4.IDX.astype("str").astype("float")

In [ ]:
!pip install scikit-learn

In [ ]:
#creditApprovalUCI.csv를 읽어보세요.
#.info()
df5 = pd.read_csv("creditApprovalUCI.csv")
df5.isnull().mean().sort_values(ascending=False)  #컬럼별 결측율, 내림차순
df5.dropna() #결측이 하나라도 있는 행 삭제
df5.fillna(0) #하나의 값으로 결측을 메꾸는...
#숫자 vs 숫자X

In [ ]:
#!pip install scikit-learn    
from sklearn.impute import SimpleImputer
import numpy as np  
df5_1 = df5.select_dtypes(include="number")  #imputing, number, mean,  median
df5_2 = df5.select_dtypes(exclude="number") #most_freuqent

imputer = SimpleImputer(strategy="mean") #숫자 컬럼, 평균, 중앙값median
df5_1_1 = pd.DataFrame( imputer.fit_transform( df5_1 ), columns=df5_1.columns )
imputer2 = SimpleImputer( strategy="most_frequent")
df5_2_1 = pd.DataFrame( imputer2.fit_transform(df5_2), columns=df5_2.columns)
pd.concat([df5_1_1, df5_2_1], axis=1)

In [ ]:
#mortDefault1.zip 다운로드->df6으로 읽으세요->@@@, qqq값을 np.nan으로 치환
#->astype으로 type을 정리->imputing
import numpy as np
df6 = pd.read_csv("mortDefault.csv")
df6["creditScore"] = df6.creditScore.replace( {"@@@":np.nan, "qqq":np.nan})
df6["creditScore"] = df6.creditScore.astype("float")
df6.drop(columns="year", inplace=True)
imputer3 = SimpleImputer()
df6_imp = pd.DataFrame( imputer3.fit_transform(df6 ), columns=df6.columns)

In [ ]:
#scaling
df6_imp.default.value_counts()  #default-> target, imbalanced, 
df6_imp.head()

from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler = StandardScaler()
scaler.fit_transform(df6_imp.drop(columns="default"))

#creditset2.csv -> default10yr->0은 normal, 1은 default->결측체크->imputing
#->숫자컬럼에 대해서만 scaling->StandardScaler ->최종 결과는 하나의 데이터프레임

df7 = pd.read_csv("creditset2.csv")
df7["default10yr"] = df7.default10yr.replace( {0:"normal", 1:"default"}    )
df7.isnull().mean()
scaler = StandardScaler()
scaler.fit(df7.drop(columns="default10yr"))
scaled = scaler.transform( df7.drop(columns="default10yr") )                              
df7_1 = pd.DataFrame( scaled,columns = df7.columns[0:3])
df7_1["default10yr"] = df7.default10yr
#standard: -,+, 값의 범위가 제한되어있지 않음
#minmax: 0~1, 값의 범위 제한, 음수없음.
scaler.inverse_transform #원복,,

In [ ]:
from sklearn.preprocessing  import LabelEncoder, OneHotEncoder
df9 = pd.read_csv("creditApprovalUCI.csv")
encoder = LabelEncoder()
encoder.fit_transform(df9.A4) #Encoding, == replace
df9["A1"] #1D
df9[["A1"]] #2D
pd.get_dummies(df9)

In [262]:
# partioning -> X_train->Standard Scaling fit, transform, X_test->transform 
df10  = pd.read_csv("creditset2.csv")
target="default10yr"

y = df10[target]
X = df10.drop(columns=target)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( 
    X, y, train_size=0.9, random_state=1, stratify=y )

scaler = StandardScaler()
X_train1 = scaler.fit_transform(X_train)
X_test1 = scaler.transform(X_test)

In [ ]:
def func1(x1):
    x1 = x1*2
    return x1

df10.age.apply(func1)  #split apply combine
df10.apply(func1)
#train_df.csv
#발화문의 길이가 20이상 30보다 작으면, 길이/2 만큼만 출력하게 해주세요
#30이상이면 15글자만 출력하게 해주세요. #함수로 만드신 후 apply적용해보세요.
df11 = pd.read_csv("train_df.csv", encoding='cp949')
def func2(sent):
    tmp = len(sent)
    if tmp <20:
        sent2 = sent
    elif tmp <30 :
        sent2 = sent[:int(tmp/2)]
    else:
        sent2 = sent[:15]
    return sent2
df11.발화문.apply(func2)

In [ ]:
# crx.data를 읽으셔서, 컬럼명은 A1~A16이 되도록 지정해주세요
df12 = pd.read_csv("crx.data", header=None) 
df12.columns = ['A'+str(i) for i in range(16) ]
df12["A15"] = df12.A15.replace( {'+':0, '-':1})# 16번째 컬럼이 +,- -> replace를 이용하셔서 1,0으로 변경해주세요.
df12.drop(columns="A13", inplace=True)# 14번째 컬럼 : 삭제
df12["A15"] = df12.A15.astype("int")# type점검->적절한 type
df12_1 = df12.select_dtypes(include="number")
df12_2 = df12.select_dtypes(exclude="number")

# 수치형-> imp, scaling(standard)
imp_n = SimpleImputer()
scaler_n = StandardScaler()
scaled = scaler_n.fit_transform( imp_n.fit_transform(df12_1) )
df12_1_1 = pd.DataFrame(scaled, columns=df12_1.columns)
#범주형->imp, get_dummies로 OHE
imp_c = SimpleImputer(strategy="most_frequent")  
imputed = imp_c.fit_transform(df12_2)
df12_2_imp = pd.DataFrame( imputed, columns=df12_2.columns)
df12_2_2 = pd.get_dummies(df12_2_imp)

df12_3 = pd.concat(  [df12_1_1, df12_2_2   ], axis=1 )# 하나의 데이터프레임으로 합쳐주세요. (pd.concat)
train, test = train_test_split(df12_3, train_size=0.9, stratify=df12_3['A15'])
train.to_csv("traintrain.csv", index=False)

In [ ]:
#df0.csv, df1.csv 
#datetime
#컬럼.dt. -> 파생변수

df14 = pd.read_csv("df0.csv", parse_dates=[0], index_col=0)
df15 = pd.read_csv("df1.csv", parse_dates=[0], index_col=0)
df14.value2+df15.value
pd.merge(df14, df15, left_index=True,right_index=True)

            value2  value  change
date
2023-03-01   10005   1000     1.5
2023-03-02   10103   1010     1.3
2023-03-05   10089   1008     0.9
2023-03-05   10089   1011     1.5
2023-03-09   10005   1000     1.5
2023-03-10   10103   1010     1.3
2023-03-14   10115   1008     0.9
2023-03-14   10115   1011     1.5